version: 2
workflows:
  version: 2
  ci:
    jobs:
    - sea
    - invoicing_app
jobs:
  sea:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle install
      - run: rake test
      - run: rubocop
      - run: bash <(curl -s https://codecov.io/bash)
  invoicing_app:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:10.6-alpine
    environment:
      - MIX_ENV: test
    working_directory: ~/repo/examples/invoicing_app
    steps:
      - checkout:
          path: ~/repo
      - run: bundle install
      - run: rake test
